### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by dukeimg** [dukeimg/filmer#1]
- [ ] Generate Pages controller
- [ ] Create landing page
- [ ] Create about page
- [ ] Install Devise
- [ ] Authentication
- [ ] Mailer
